name: rae_bluetooth # search/replace all occurances of 'rae_bluetooth' to the new package name
description: Template for Flutter Package project.
version: 0.0.7+4
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0" #Dart SDK 2021-12-08
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.2.0
  intl: ^0.17.0
  permission_handler: ^8.3.0

dev_dependencies:
  test: ^1.20.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/accelerometer_abstract.png
    - assets/accelerometer.png
    - assets/bluetooth_denied.png
    - assets/bluetooth_off.png
    - assets/bluetooth_streaming.png
    - assets/bluetooth.png
    - assets/checkmark.png
    - assets/circle_cross_narrow.png
    - assets/circle_cross.png
    - assets/circle_question_mark.png
    - assets/circle_x.png
    - assets/no_data_watch.png
    - assets/no_data.png
    - assets/no_watch.png
    - assets/notpaired.png
    - assets/protected.png
    - assets/receiving_data.gif
    - assets/shield.png
    - assets/transmission.png
