name: rae_bluetooth # search/replace all occurances of 'rae_bluetooth' to the new package name
description: Template for Flutter Package project.
version: 0.0.7+2
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0" #Dart SDK 2021-12-08
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.2.0
  intl: ^0.17.0
  permission_handler: ^8.3.0

dev_dependencies:
  test: ^1.20.0

flutter:
  uses-material-design: true
  generate: true
